import 'package:cloud_firestore/cloud_firestore.dart';

class TaskDM {
  // we put an initial value here as we get the id from firebase autogenerated id
  String theId = '';
  String theTitle;
  String theDescription;
  DateTime theDate;
  bool isDone;
  TaskDM({
    required this.theId,
    required this.theTitle,
    required this.theDescription,
    required this.theDate,
    this.isDone = false,
  });

  // this is like translating from one language to another
  // it is better to write these 2 functions with the data model you are translating
  // make the fromJason functions a named constructor for easier access
  // we are making all of this to send and receive from firebase
  TaskDM.fromJason(Map<String, dynamic> jason)
      : this(
          theId: jason['theId'],
          theTitle: jason['theTitle'],
          theDescription: jason['theDescription'],
          theDate: (jason['theDate'] as Timestamp).toDate(), // important
          isDone: jason['isDone'],
        );

  Map<String, dynamic> toJason() {
    return {
      'theId': theId,
      'theTitle': theTitle,
      'theDescription': theDescription,
      'theDate': Timestamp.fromDate(theDate), // important
      'isDone': isDone
    };
  }
}
